### ISSUE TITLE
Review Feedback, and add development suggestions to fix common problems

### ISSUE THREAD

**Issue by douglowe** [carpentries-incubator/python-intermediate-development-earth-sciences#10]
Read through feedback from last course, and add ideas for material development from these to this issue, for discussion at next meeting.

**Comment by anenadic** [comment]
Add link to feedback results

**Comment by douglowe** [comment]
https://codimd.carpentries.org/2023-03-27-manchester-intermediate-swc-trainers
https://codimd.carpentries.org/2023-03-27-manchester-intermediate-swc

**Comment by douglowe** [comment]
Development ideas from the trainers review:

- We need to work out how to have people work with CI
  - pre-commit (?) added to the material - ambitious goal but can be useful - automatic code fixing
- YAML context needs to be added
- Look into current Python packaging practices for the next run
  - Switch to TOML
  - Packaging workflows - poetry/hatch/ruff
