### ISSUE TITLE
Advertising for the course

### ISSUE THREAD

**Issue by douglowe** [carpentries-incubator/python-intermediate-development-earth-sciences#11]
Anja to follow up with participants from last course, to get more feedback.

And will ask them to tell colleagues about course too.

**Comment by anenadic** [comment]
Advertise via SSI social media and Fellows

**Comment by anenadic** [comment]
Last year's SSI news item: https://www.software.ac.uk/news/nerc-workshop-intermediate-research-software-skills-atmospheric-sciences

**Comment by AnjaLeBlanc** [comment]
Meeting with Dave today: yes we push through the same mailing lists as last time. Supervisors pointing the course out to their students has worked.

**Comment by AnjaLeBlanc** [comment]
Application process running: 05/12/23  -- 17 applications
