### ISSUE TITLE
Create Sign Up Form

### ISSUE THREAD

**Issue by douglowe** [carpentries-incubator/python-intermediate-development-earth-sciences#12]
Create new Qualtrics form for sign-ups.

Or look at using EventBrite - ask Gillian what R-IT use, or we can use SSI for this.

**Comment by anenadic** [comment]
From last year: https://www.qualtrics.manchester.ac.uk/jfe/preview/previewId/d8ba1045-6655-4a26-af41-0d03d6cebda6/SV_87F94dIoT1aRwto?Q_CHL=preview&Q_SurveyVersionID=current

**Comment by anenadic** [comment]
NERC application form edit version on Qualtrics: https://www.qualtrics.manchester.ac.uk/survey-builder/SV_87F94dIoT1aRwto/edit

**Comment by anenadic** [comment]
Ask Gillian in the first instance to use EventBrite to replicate the form from last year @AnjaLeBlanc .

**Comment by AnjaLeBlanc** [comment]
Gillian has an EventBrite RIT account, but EventBrite just change to charging for Events > 25 people.
It is not the £8, but the hassle to get someone to pay :-(

**Comment by anenadic** [comment]
Oh dear. I’ll have a look if it is the same for the SSI EventBrite account.


Dr Aleksandra Nenadic
Training Lead
Software Sustainability Institute<https://www.software.ac.uk/>
[signature_1837552402]<https://twitter.com/SoftwareSaved>[signature_2897828511]<https://www.linkedin.com/company/software-sustainability-institute>

From: Anja Le Blanc ***@***.***>
Date: Monday, 9 October 2023 at 22:17
To: UoMResearchIT/python-intermediate-development-nerc ***@***.***>
Cc: Aleksandra Nenadic ***@***.***>, Assign ***@***.***>
Subject: Re: [UoMResearchIT/python-intermediate-development-nerc] Create Sign Up Form (Issue #12)

Gillian has an EventBrite RIT account, but EventBrite just change to charging for Events > 25 people.
It is not the £8, but the hassle to get someone to pay :-(

**Comment by AnjaLeBlanc** [comment]
Comment from Gillian:
We can use RIT Eventbrite and IT will pay for it via their Credit card. It is only 7.99.

Some amendment to last years form to add demographics questions.

**Comment by anenadic** [comment]
Great news!

**Comment by AnjaLeBlanc** [comment]
Gillian created a version, we go through this on Monday, 23rd Oct

**Comment by anenadic** [comment]
Is there a team meeting on Monday 23rd October or is this internal @AnjaLeBlanc ?
