### ISSUE TITLE
Write / Update Advertisement Text

### ISSUE THREAD

**Issue by douglowe** [carpentries-incubator/python-intermediate-development-earth-sciences#15]

**Comment by anenadic** [comment]
From last year: 

https://www.software.ac.uk/news/nerc-workshop-intermediate-research-software-skills-atmospheric-sciences

https://uomresearchit.github.io/python-intermediate-development-nerc/index.html

**Comment by AnjaLeBlanc** [comment]
Sign up form from last year
https://www.qualtrics.manchester.ac.uk/jfe/preview/previewId/d8ba1045-6655-4a26-af41-0d03d6cebda6/SV_87F94dIoT1aRwto?Q_CHL=preview&Q_SurveyVersionID=current

**Comment by AnjaLeBlanc** [comment]
https://livemanchesterac-my.sharepoint.com/:w:/g/personal/anja_leblanc_manchester_ac_uk/EZPpOiJzBcBOtKU4x9wMOTQBrV3_YMOkYMdvULJIrDR1uw?e=Nw2flO

Please review!

**Comment by anenadic** [comment]
Looking good @AnjaLeBlanc. I cannot comment in the document directly (no edit access) - the only thing that we did no do last year and not sure we will this time either is provide "individual self-learning sessions aided by helpers". So I'd just remove that.

**Comment by AnjaLeBlanc** [comment]
@anenadic , I removed that statement. I have now changed the permissions for everyone.

**Comment by douglowe** [comment]
I've made a small adjustment to the text (see suggested edits), otherwise I think it's good to go.
