### ISSUE TITLE
Room booking

### ISSUE THREAD

**Issue by douglowe** [carpentries-incubator/python-intermediate-development-earth-sciences#16]

**Comment by anenadic** [comment]
Rooms: Collab 1 & 2, Computer Science, Kilburn Building, Oxford Road M13 9PL

**Comment by anenadic** [comment]
Email thread wrt room booking:

Hi Erika,

Many thanks for your help with booking all these rooms.

Best regards,

Aleks

. . . . . . . . . . . . . . . . . . . . .
Dr Aleksandra Nenadic (she/her) | Training Lead
Software Sustainability Institute
2.71 Kilburn Building, University of Manchester, Oxford Road, M13 9PL
[www.software.ac.uk](http://www.software.ac.uk/)
