### ISSUE TITLE
Helpers to recruit

### ISSUE THREAD

**Issue by douglowe** [carpentries-incubator/python-intermediate-development-earth-sciences#21]
2022 course (not asked yet):
Nourahn

Current Helpers:
Doug (trainer)
Anja
Aman
Scott
Emma
Ann
Aleks
Andrew Walker (external)

Major help needed for:
- SSH key setup at start
- CI/CD on github

**Comment by AnjaLeBlanc** [comment]
Dominic Orchard from Institute of Computing for Climate Science ICCE to co-deliver a section.
