### ISSUE TITLE
Liaise with Andrew Walker (helper from Oxford) closer to the workshop

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development-earth-sciences#25]
- check Andrew's plans - how many days he is staying
- offer Andrew help with booking accommodation (he is covering his costs though)
- check if Andrew is attending dinners/socials

**Comment by AnjaLeBlanc** [comment]
Andew emailed. 
I pointed him to our web site for infos, requested dietary requirements, and asked if he wanted to meet for a meal on Sunday night.
