### ISSUE TITLE
Move software template repo into carpentries incubator

### ISSUE THREAD

**Issue by douglowe** [carpentries-incubator/python-intermediate-development-earth-sciences#28]

**Comment by douglowe** [comment]
Software template has been moved to https://github.com/carpentries-incubator/python-intermediate-rivercatchment

@anenadic - please could you ask Toby to transfer ownership to us?

**Comment by douglowe** [comment]
Link on course material has been updated (rather than create PR, I accidentally pushed straight to gh-pages branch...)

**Comment by anenadic** [comment]
> Software template has been moved to https://github.com/carpentries-incubator/python-intermediate-rivercatchment
> 
> @anenadic - please could you ask Toby to transfer ownership to us?

Asked @tobyhodges on Slack,
