### ISSUE TITLE
create website for workshop

### ISSUE THREAD

**Issue by douglowe** [carpentries-incubator/python-intermediate-development-earth-sciences#30]
Create a website, similar to last year, for the workshop

**Comment by anenadic** [comment]
Created temporary website repo at: https://github.com/anenadic/2024-03-18-manchester-intermediate-swc. Once detached from the original one it was forked from I will move it to SSI GitHub org, unless @douglowe tells me otherwise.

**Comment by anenadic** [comment]
Schedule needs updating

**Comment by anenadic** [comment]
Done -the workshop website is at: https://github.com/softwaresaved/2024-03-18-manchester-intermediate-swc/tree/gh-pages. Let me know if you want it moved somewhere else @douglowe.
