### ISSUE TITLE
change all the screenshots to VS Code

### ISSUE THREAD

**Issue by douglowe** [carpentries-incubator/python-intermediate-development-earth-sciences#4]

**Comment by AnnAnnFryingPan** [comment]
Doug needs to make changes to the incubuator version of the repo, so currently this is just my branch, with no PR.
Branch name: feat/issue-4_update_screenshots
(https://github.com/carpentries-incubator/python-intermediate-development-earth-sciences/tree/feat/issue-4_update_screenshots)

**Comment by douglowe** [comment]
New PR, replacing the PR above that I broke:
https://github.com/carpentries-incubator/python-intermediate-development-earth-sciences/pull/37

**Comment by AnnAnnFryingPan** [comment]
@douglowe and @Scottan I believe I have addressed all the comments/corrections so far, for the PR
@emmasimp please take the latest version and add any comments to the PR (see Doug's link in above comment)
