### ISSUE TITLE
Corrections to code in _episode 22

### ISSUE THREAD

**Issue by emmasimp** [carpentries-incubator/python-intermediate-development-earth-sciences#52]
Missing commas in solution code.

![missing_commas](https://github.com/carpentries-incubator/python-intermediate-development-earth-sciences/assets/29974362/462089cc-7225-4ab3-b8da-ab22f2082e0f)

Commas needed at the green arrows.

Extra bracket needs deleting

![Extra_bracket](https://github.com/carpentries-incubator/python-intermediate-development-earth-sciences/assets/29974362/3c7bd4b6-9662-4bbb-8954-865a66758921)

daily_max needs replacing with daily_min:

![daily_max_to_daily_min](https://github.com/carpentries-incubator/python-intermediate-development-earth-sciences/assets/29974362/fa1b1409-00b3-4f00-9912-dc276f64e92c)

**Comment by douglowe** [comment]
thanks :)
