### ISSUE TITLE
_episode 23 error with yml code

### ISSUE THREAD

**Issue by emmasimp** [carpentries-incubator/python-intermediate-development-earth-sciences#64]
I couldnt get the workflow actions to run with the following lines:

    runs-on: {% raw %}${{ matrix.os }}{% endraw %}

    python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

Removing the {% raw %} and {% endraw %} solves the issue

**Comment by douglowe** [comment]
I've had a quick look into this, and it appears that we need the {% raw %} and {% endraw %} strings to stop the ${{ }} code from being interpreted during the creation of the web page. We'll have to leave them in the source code - will just have to make sure we use the rendered pages for our instructions (in which these don't display).
