### ISSUE TITLE
Move material into carpentries incubator

### ISSUE THREAD

**Issue by douglowe** [carpentries-incubator/python-intermediate-development-earth-sciences#9]
Find out what we will need to do.

And we need to decide on a better name for the repository (maybe 'environmental-science' instead of 'nerc'?).

**Comment by anenadic** [comment]
Rename repo to python-intermediate-development-environmental-sciences

**Comment by anenadic** [comment]
Submitted a request to move the repo the Incubator: https://github.com/carpentries-incubator/proposals/issues/177

**Comment by douglowe** [comment]
How about:
**Intermediate Research Software Development for Environmental Sciences**

**Comment by douglowe** [comment]
This has now been moved.

The project board remains within the UoMResearchIT organisation - I've updated links to this though.

**Comment by douglowe** [comment]
We need to get our collaborators added to the Carpentries Incubator. And I'll update the README, to add an acknowledgement for UoM.

**Comment by douglowe** [comment]
I need to chase up with Toby on this.

**Comment by anenadic** [comment]
https://github.com/carpentries-incubator/python-intermediate-development-earth-sciences

**Comment by anenadic** [comment]
This has not been completed @douglowe - Toby sent invitations to all team members.
